# Generated by Django 3.0.8 on 2021-10-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_adocao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cachorro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chip', models.IntegerField(max_length=6)),
                ('nome', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chip', models.IntegerField(max_length=6)),
                ('nome', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chip', models.IntegerField(max_length=6)),
                ('nome', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.IntegerField(max_length=4)),
                ('cor', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='apoio',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
