# Generated by Django 3.0.8 on 2021-10-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_adocao', '0002_auto_20211002_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='foto1',
            field=models.FileField(blank=True, upload_to='pi/media'),
        ),
    ]
