# Generated by Django 3.0.8 on 2021-10-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_adocao', '0005_auto_20211008_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachorro',
            name='foto0',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='cachorro',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='gato',
            name='foto0',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='gato',
            name='foto1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='gato',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='outro',
            name='foto0',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='outro',
            name='foto1',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='outro',
            name='foto2',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
